### ISSUE TITLE
use included spark-avro jars

### ISSUE THREAD

**Issue by mattpollock** [chezou/sparkavro#4]
The current implementation always uses an empty `jars=` argument to `sparklyr::spark_dependency` and adds the spark-packages argument. This works great for systems that can connect out to spark packages or for R users who know how to manage local maven/ivy repos. However since the jars are packaged up in the `inst` directory anyway, it would simplify things for users to just use those jars that they've already downloaded when installing `sparkavro`.

**Comment by mattpollock** [comment]
see PR #5

**Comment by chezou** [comment]
I attached those jars unintentionally. I removed them at #6 .
