### ISSUE TITLE
spark_write_avro fails when run on Spark 2.3

### ISSUE THREAD

**Issue by dkincaid** [chezou/sparkavro#9]
Right now `spark_write_avro` fails when run on Spark 2.3. The version of spark-avro used needs to be upgraded to 4.0.0. I will submit a pull request with the fix.

**Comment by chezou** [comment]
Thanks for sending a PR!

**Comment by chezou** [comment]
JFYI, uploaded 0.2.0 on CRAN https://cran.r-project.org/web/packages/sparkavro/index.html

**Comment by dkincaid** [comment]
Thank you for getting it in there so fast!
